services:
  wiremock:
    container_name: wiremock
    hostname: wiremock
    image: wiremock/wiremock
    volumes:
      - ./src/apiTest/resources:/home/wiremock/mappings
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8083/__admin/health || exit 1']
    environment:
      WIREMOCK_OPTIONS: "--port=8083"
    ports:
      - "8083:8083"

  azurite:
    container_name: azurite
    hostname: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite --loose --location /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --oauth basic --cert /root/cert.pem --key /root/key.pem
    volumes:
      - ./azurite:/root
    healthcheck:
      test: nc 127.0.0.1 10000 -z
      interval: 1s
      retries: 30
    environment:
      AZURITE_ACCOUNTS: "test:password"
    ports:
      - "10002:10002"

  azurite_init:
    container_name: azurite_init
    image: mcr.microsoft.com/azure-cli
    volumes:
      - ./azurite:/opt
    command: /opt/init.sh
    depends_on:
      azurite:
        condition: service_healthy
    environment:
      REQUESTS_CA_BUNDLE: /opt/cert.pem
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=test;AccountKey=password;BlobEndpoint=https://azurite:10000/test;QueueEndpoint=https://azurite:10001/test;TableEndpoint=https://azurite:10002/test;

  azurite_data:
    container_name: azurite_data
    image: python
    volumes:
      - ./azurite:/opt
    command: /opt/data.sh
    depends_on:
      azurite_init:
        condition: service_completed_successfully
    environment:
      AZURE_ENDPOINT: https://azurite:10002/test
      AZURE_CREDS_KEY: password
      AZURE_CREDS_NAME: test
      REQUESTS_CA_BUNDLE: /opt/cert.pem

  app:
    container_name: app
    build:
      context: .
    depends_on:
      wiremock:
        condition: service_healthy
      azurite_data:
        condition: service_completed_successfully
    environment:
      CP_AZURE_CREDS_NAME: test
      CP_AZURE_TOKEN_TYPE: TEST
      CP_AZURE_CLOUD_TYPE: AZURITE
      CP_AZURE_TABLE_ENDPOINT: https://azurite:10002/test
      CP_AZURE_FABRIC_BASE_URL: http://wiremock:8083/
      CP_AZURE_FABRIC_WORKSPACE_ID: 5323aeaf-c852-4a6b-9d37-5acd8cda6b87
      CP_AZURE_FABRIC_ITEM_ID: 9a13afd6-d911-4845-b7a6-747574908323
      AUDITREPORTS_SYSTEM_USER_ID: test
    ports:
      - "8082:8082"
