services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8083/__admin/health || exit 1']
    environment:
      WIREMOCK_OPTIONS: "--port=8083"
    volumes:
      - ./src/apiTest/resources:/home/wiremock/mappings
    ports:
      - "8083:8083"

  app:
    container_name: app
    build:
      context: .
    depends_on:
      wiremock:
        condition: service_healthy
    environment:
      CP_CAR_BASE_URL: http://wiremock:8083/
      CP_AZURE_TOKEN_TYPE: TEST
      CP_AZURE_FABRIC_BASE_URL: http://wiremock:8083/
      CP_AZURE_FABRIC_WORKSPACE_ID: 5323aeaf-c852-4a6b-9d37-5acd8cda6b87
      CP_AZURE_FABRIC_ITEM_ID: 9a13afd6-d911-4845-b7a6-747574908323
    ports:
      - "8082:8082"
